### ISSUE TITLE
When I run mvn test, it warns "WARN  c.l.a.i.c.util.TransportTypeProvider - Inconsistent Netty versions detected:"

### ISSUE THREAD

**Issue by chetanpan** [karatelabs/karate-todo#1]
[main] WARN  c.l.a.i.c.util.TransportTypeProvider - Inconsistent Netty versions detected: {netty-buffer=netty-buffer-4.1.110.Final.2e218bbd0a, netty-codec=netty-codec-4.1.110.Final.2e218bbd0a, netty-codec-dns=netty-codec-dns-4.1.110.Final.2e218bbd0a, netty-codec-haproxy=netty-codec-haproxy-4.1.110.Final.2e218bb (repository: dirty), netty-codec-http=netty-codec-http-4.1.110.Final.2e218bbd0a, netty-codec-http2=netty-codec-http2-4.1.110.Final.2e218bb (repository: dirty), netty-codec-mqtt=netty-codec-mqtt-4.1.92.Final.acc3525 (repository: dirty), netty-codec-socks=netty-codec-socks-4.1.110.Final.2e218bb (repository: dirty), netty-common=netty-common-4.1.110.Final.2e218bbd0a, netty-handler=netty-handler-4.1.110.Final.2e218bbd0a, netty-handler-proxy=netty-handler-proxy-4.1.110.Final.2e218bb (repository: dirty), netty-resolver=netty-resolver-4.1.110.Final.2e218bbd0a, netty-resolver-dns=netty-resolver-dns-4.1.110.Final.2e218bbd0a, netty-resolver-dns-classes-macos=netty-resolver-dns-classes-macos-4.1.110.Final.2e218bbd0a, netty-resolver-dns-native-macos=netty-resolver-dns-native-macos-4.1.110.Final.2e218bbd0a, netty-transport=netty-transport-4.1.110.Final.2e218bbd0a, netty-transport-classes-epoll=netty-transport-classes-epoll-4.1.110.Final.2e218bb (repository: dirty), netty-transport-classes-kqueue=netty-transport-classes-kqueue-4.1.110.Final.2e218bbd0a, netty-transport-native-epoll=netty-transport-native-epoll-4.1.110.Final.2e218bb (repository: dirty), netty-transport-native-kqueue=netty-transport-native-kqueue-4.1.110.Final.2e218bbd0a, netty-transport-native-unix-common=netty-transport-native-unix-common-4.1.110.Final.2e218bbd0a} This means 1) you specified Netty versions inconsistently in your build or 2) the Netty JARs in the classpath were repackaged or shaded incorrectly. Specify the '-Dcom.linecorp.armeria.warnNettyVersions=false' JVM option to disable this warning at the risk of unexpected Netty behavior, if you think it is a false positive.

**Comment by ptrthomas** [comment]
this is not an issue and just a warning, because it is for starting a demo server used
